import {
  Award,
  Banknote,
  Bot,
  BrainCircuit,
  Briefcase,
  Bug,
  Building2,
  ChartPie,
  CircleHelp,
  Coffee,
  Coins,
  Crown,
  Flag,
  Flame,
  Gem,
  Ghost,
  GitCommitHorizontal,
  GitPullRequest,
  Hand,
  Infinity as InfinityIcon,
  Landmark,
  Layers,
  type LucideIcon,
  Medal,
  MessageSquareX,
  Monitor,
  Moon,
  Power,
  Rocket,
  ScanEye,
  ShoppingCart,
  Sparkles,
  Swords,
  Target,
  Ticket,
  Timer,
  TrendingUp,
  UserPlus,
  Users,
  UsersRound,
  Wallet,
} from "lucide-react";

import type { AchievementGroup, AchievementId } from "@/game/content";

/** One icon per achievement, as a console shows a badge. */
export const ACHIEVEMENT_ICONS: Record<AchievementId, LucideIcon> = {
  first_ticket: Ticket,
  first_commit: GitCommitHorizontal,
  first_ai_commit: Bot,
  first_review: ScanEye,
  first_pr: GitPullRequest,
  first_delivery: Rocket,
  first_payday: Banknote,
  first_purchase: ShoppingCart,
  first_fix: Bug,
  first_skill: Sparkles,
  first_sprint: Flag,
  first_hire: UserPlus,
  first_tier: TrendingUp,
  first_site: Building2,
  tier_3: Gem,
  tier_6: InfinityIcon,
  team_10: Users,
  team_30: UsersRound,
  all_sites: Landmark,
  death_star: Moon,
  all_acquisitions: Briefcase,
  market_half: ChartPie,
  first_million: Coins,
  first_billion: Crown,
  sprints_50: Timer,
  account_level_10: Medal,
  account_tickets_1000: Award,
  works_on_my_machine: Monitor,
  liquid_cooling: Coffee,
  hack_won: Ghost,
  caught: Hand,
  overheated: Flame,
  retired: Power,
  branch_wars: Swords,
  tough_month: Wallet,
  ultimate_question: CircleHelp,
  no_longer_required: BrainCircuit,
  house_of_cards: Layers,
  changes_requested: MessageSquareX,
  hostile_takeover: Target,
};

/** The route is the accent, prestige is gold, a secret is the machine's violet. */
export const GROUP_TONE: Record<AchievementGroup, string> = {
  route: "text-cyber",
  prestige: "text-energy",
  secret: "text-ai",
};
